### ISSUE TITLE
Adding .zip extension if directory name has extension

### ISSUE THREAD

**Issue by jemise111** [bitrise-steplib/steps-create-zip#5]
Hello, thanks for the helpful step!

I'm having a small issue - I specify a directory path to be zipped and it is successfully but it is not given an extension of ".zip".

Is it possible that it skips adding the ".zip" if the "Source directory path" already has an extension.

In my case I'm trying to zip an iOS app - which is a directory that has the extension ".app".

I think maybe this line: https://github.com/bitrise-steplib/steps-create-zip/blob/master/main.go#L98 should be:

```
if filepath.Ext(destination) != "zip" {
```

What do you think?

Thanks!

**Comment by trapacska** [comment]
Hey @jemise111!

The step works like:
- if the destination path has an extension then use that
- if the destination path has no extension then it will append a ".zip" to the path

When you set a path as a destination that has a suffix os .app, then it is an extension and will be used that. It does not matter if it is a directory or a file, because it is an extension. Of course it can be a directory which is understandable by MacOS, and can be a binary file as well.

Closing the issue as it is not an exact issue with the step itself. Feel free to re-open if you encounter any issues with the step

Happy Building 🚀
